{{ if .Values.serviceMonitor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-connector.appname" . }}-metrics
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "mongo-connector.labels" . | nindent 4 }}
    scrape-metrics: "true"
  {{ with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 10080
      targetPort: http
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mongo-connector.appname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
