# templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "mongo-connector.appname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongo-connector.labels" . | nindent 4 }}
  {{ with .Values.serviceAccount.annotations -}}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end -}}